# Generated by Django 5.0.3 on 2024-03-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Nazwa produktu')),
                ('price', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Cena produktu')),
                ('quantity', models.IntegerField(default=0, verbose_name='Ilosć')),
                ('category', models.IntegerField(choices=[(0, 'Jedzenie'), (1, 'Napoje')], verbose_name='Kategoria')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis produktu')),
            ],
        ),
    ]
